#!/usr/bin/env python3
"""
gen_reloc_cmake.py — walk decomp/src/relocData/ and emit a CMake include
file with one add_reloc_resource() call per file we can build from source.

Output goes to <build>/reloc_data_targets.cmake. The top-level CMakeLists
includes() it after RelocData.cmake. Re-running the script is idempotent
and side-effect-free (the output is regenerated on each cmake configure).

Eligibility filter (M3 best-effort):
  - .c file exists (skip JP-only files where only `<id>_<name>.jp.c` is present)
  - .reloc file exists (skip files with no relocation metadata)
  - .c does not #include any *.inc.c file (those need upstream's
    `make extract` step which the port doesn't run)
  - .reloc has no `extern` lines (extern handling needs a dep_file_id
    index that's not yet built — M3 follow-up)

The remainder (intern-only, self-contained C source) builds end-to-end
through tools/build_reloc_resource.py.

Usage:
    gen_reloc_cmake.py
        --reloc-dir   <decomp/src/relocData>
        --reloc-table <port/resource/RelocFileTable.cpp>
        --output      <build>/reloc_data_targets.cmake
        [--report     <build>/reloc_data_eligibility.json]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Matches a line `	"reloc_<cat>/<Name>", /* N */`
TABLE_RE = re.compile(r'^\s*"([^"]+)",\s*/\*\s*(\d+)\s*\*/')

# Matches `<id>_<Name>.c` filename
RELOCDATA_FILE_RE = re.compile(r"^(\d+)_([A-Za-z0-9_]+)\.c$")


def parse_reloc_table(path: Path) -> dict[int, str]:
    out: dict[int, str] = {}
    for line in path.read_text().splitlines():
        m = TABLE_RE.match(line)
        if m:
            out[int(m.group(2))] = m.group(1)
    return out


def has_inc_c_include(c_path: Path) -> bool:
    """True if the .c file #includes any *.inc.c — those require upstream's
    make-extract step which the port doesn't run."""
    try:
        text = c_path.read_text()
    except Exception:
        return True  # be conservative; treat as ineligible
    return bool(re.search(r'#\s*include\s+[<"][^>"]*\.inc\.c[>"]', text))


def has_extern_reloc(reloc_path: Path) -> bool:
    """True if any line starts with 'extern '."""
    try:
        for line in reloc_path.read_text().splitlines():
            if line.strip().startswith("extern "):
                return True
    except Exception:
        return False
    return False


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--reloc-dir", type=Path, required=True)
    ap.add_argument("--reloc-table", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument("--report", type=Path, default=None)
    args = ap.parse_args()

    table = parse_reloc_table(args.reloc_table)
    if not table:
        print(f"error: no entries parsed from {args.reloc_table}", file=sys.stderr)
        return 2

    eligible: list[tuple[int, str, str]] = []  # (file_id, c_path_rel, resource_path)
    skipped: dict[str, list[int]] = {
        "no_c_file": [],
        "no_reloc_file": [],
        "no_table_entry": [],
        "needs_inc_c": [],
        "has_externs": [],
    }

    for c_path in sorted(args.reloc_dir.glob("*.c")):
        m = RELOCDATA_FILE_RE.match(c_path.name)
        if not m:
            continue
        fid = int(m.group(1))

        reloc_path = c_path.with_suffix(".reloc")
        if not reloc_path.exists():
            skipped["no_reloc_file"].append(fid)
            continue

        if fid not in table:
            skipped["no_table_entry"].append(fid)
            continue

        if has_inc_c_include(c_path):
            skipped["needs_inc_c"].append(fid)
            continue

        if has_extern_reloc(reloc_path):
            skipped["has_externs"].append(fid)
            continue

        eligible.append((fid, c_path.name, table[fid]))

    # Emit CMake include
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w") as f:
        f.write("# Auto-generated by tools/gen_reloc_cmake.py — do not edit.\n")
        f.write(f"# {len(eligible)} eligible relocData files of {len(eligible) + sum(len(v) for v in skipped.values())} total.\n\n")
        for fid, basename, res_path in eligible:
            f.write(
                f'add_reloc_resource({fid} '
                f'${{CMAKE_SOURCE_DIR}}/decomp/src/relocData/{basename} '
                f'"{res_path}")\n'
            )

    print(f"emitted {args.output} ({len(eligible)} eligible)")
    print(f"  skipped — no .c (JP-only files):    {len(skipped['no_c_file'])}")
    print(f"  skipped — no .reloc:                {len(skipped['no_reloc_file'])}")
    print(f"  skipped — no table entry:           {len(skipped['no_table_entry'])}")
    print(f"  skipped — needs upstream .inc.c:    {len(skipped['needs_inc_c'])}")
    print(f"  skipped — has extern reloc:         {len(skipped['has_externs'])}")

    if args.report is not None:
        args.report.write_text(json.dumps(
            {"eligible_count": len(eligible),
             "eligible": [fid for fid, _, _ in eligible],
             **skipped},
            indent=2))
        print(f"wrote eligibility report {args.report}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
