#!/usr/bin/env python3
"""
generate_reloc_table.py — Reads yamls/us/reloc_*.yml and generates
port/resource/RelocFileTable.cpp, a file_id-to-resource-path lookup table.

Usage:
    python tools/generate_reloc_table.py
"""

import os
import re
import sys
from pathlib import Path

YAML_DIR = Path("yamls/us")
OUTPUT   = Path("port/resource/RelocFileTable.cpp")
FILE_COUNT = 2132


def parse_yaml_entries(yaml_dir: Path) -> dict[int, str]:
    """Parse all reloc_*.yml files and return {file_id: entry_name}."""
    entries = {}

    for fname in sorted(yaml_dir.iterdir()):
        if not fname.name.startswith("reloc_") or not fname.suffix == ".yml":
            continue

        content = fname.read_text(encoding="utf-8")
        current_name = None

        for line in content.split("\n"):
            m = re.match(r"^([A-Za-z_]\w*):\s*$", line)
            if m:
                current_name = m.group(1)
                continue
            if current_name:
                m2 = re.match(r"^\s+file_id:\s+(\d+)", line)
                if m2:
                    fid = int(m2.group(1))
                    if fid in entries:
                        print(f"WARNING: duplicate file_id {fid}: "
                              f"{entries[fid]} vs {current_name}", file=sys.stderr)
                    entries[fid] = current_name
                    current_name = None

    return entries


def generate(entries: dict[int, str], output: Path) -> None:
    """Write the C++ lookup table."""
    lines = []
    lines.append("/**")
    lines.append(" * RelocFileTable.cpp - Auto-generated file_id to resource path mapping.")
    lines.append(" *")
    lines.append(" * Generated by: python tools/generate_reloc_table.py")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "RelocFileTable.h"')
    lines.append("")
    lines.append(f"const char* const gRelocFileTable[RELOC_FILE_COUNT] = {{")

    for i in range(FILE_COUNT):
        name = entries.get(i)
        if name is None:
            lines.append(f"\tNULL, /* {i} - MISSING */")
        else:
            lines.append(f'\t"{name}", /* {i} */')

    lines.append("};")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {output} ({len(entries)} entries)")


def main():
    os.chdir(Path(__file__).resolve().parent.parent)
    entries = parse_yaml_entries(YAML_DIR)

    if len(entries) != FILE_COUNT:
        print(f"WARNING: expected {FILE_COUNT} entries, got {len(entries)}",
              file=sys.stderr)

    missing = set(range(FILE_COUNT)) - set(entries.keys())
    if missing:
        print(f"WARNING: missing file_ids: {sorted(missing)[:20]}...",
              file=sys.stderr)

    generate(entries, OUTPUT)


if __name__ == "__main__":
    main()
